import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const REPO_NAME = "88code-sdk"

const outDir = path.join(process.cwd(), "dist", "client")
const indexPath = path.join(outDir, "index.html")

function patchHtml(html) {
  // 1) Remove modulepreload links: they appear before our base script and would resolve incorrectly.
  html = html.replace(/<link rel="modulepreload"[^>]*\/>/g, "")

  // 2) Replace TanStack Start's "/./assets/..." with base-aware relative URLs.
  html = html.replaceAll("/./assets/", "assets/")

  // 3) Make internal links base-aware (GH Pages project path vs custom domain).
  //    Root path needs to be explicit.
  html = html.replace(/href="\/"/g, 'href="./"')
  html = html.replace(/href="\//g, 'href="')

  // 4) Insert a parser-blocking early base writer.
  //    This guarantees `<base>` exists before any subsequent relative URLs are parsed.
  const earlyBaseWriter = `<script>(function(){try{var repo="${REPO_NAME}";var p=location.pathname||"/";var isProject=p==="/"+repo||p.startsWith("/"+repo+"/");var base=isProject?"/"+repo+"/":"/";window.__APP_BASE__=base;document.write('<base href="'+base+'">');}catch(_){}})();</script>`
  // Remove any existing base scripts generated by the app layer.
  html = html.replace(/<script>[^<]*window\.__APP_BASE__[^<]*<\/script>/g, "")

  // Inject right after viewport meta (keeps charset/meta first, but before any <link>/<script> that uses relative URLs).
  html = html.replace(
    /(<meta name="viewport"[^>]*\/>)/,
    `$1${earlyBaseWriter}`
  )

  return html
}

async function main() {
  const raw = await readFile(indexPath, "utf8")
  const patched = patchHtml(raw)

  await writeFile(indexPath, patched, "utf8")
  await writeFile(path.join(outDir, "404.html"), patched, "utf8")
  await writeFile(path.join(outDir, ".nojekyll"), "", "utf8")
}

await main()
